# 正式环境(prod) or 测试环境(dev)


spring:
  profiles:
    active: prod
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 1
#    host: 192.168.213.128
    host: localhost
    #    host: 10.10.61.40
    port: 6379
    #    password: djsaiodjias4556564..3lk23o1dskja546dsaopj
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    #      ruijing服务器redis密码
  #    password: sdkoadjsaidjasdisa,djsiaodjsai231232
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 12000

mybatis-plus:
  global-config:
    db-config:
      #自动递增
      id-type: auto




minio:
  endpoint: http://10.10.61.40:9000
  accessKey: admin
  secretKey: admin123
  bucket: ruijing
# 日志名称
logging:
  # 日志名称
  file:
    name: ruijing-admin.log
  logback:
    rollingpolicy:
      # 超过1MB重新创建日志文件
      max-file-size: 1MB
      # 重新创建的日志文件命名规则
      file-name-pattern: ruijing-admin.%d{yyyy-MM-dd}.%i.log
  level:
    com.example.mybatis_plus.sys.mapper: debug









