# 正式环境(prod) or 测试环境(dev)


spring:
  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 175.178.189.129
    port: 6379
    password: djsaiodjias4556564..3lk23o1dskja546dsaopj
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

server:
  port: 12000

mybatis-plus:
  global-config:
    db-config:
      #自动递增
      id-type: auto
      #日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


minio:
  endpoint: http://175.178.189.129:9000
  accessKey: admin
  secretKey: admin123
  bucket: ruijing








